POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Vaskyat",
    "password": "Lauta+123"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "vaskyat",
    "password": "lauta+123"
}

###