POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "The first Blog ever in this database",
    "author": "William McMahon",
    "url": "http://www.williamblog.com/",
    "likes": 25
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "How to Skate  without socks",
    "author": "Paulo Maninho",
    "url": "http://www.skating-feets.org/",
    "likes": 127
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZhc2t5YXQiLCJpZCI6IjYzMmYwZTZlMjVlZGZjNjMxOGRjMDFhYyIsImlhdCI6MTY5ODYwOTM2OSwiZXhwIjoxNjk4NjEyOTY5fQ.LvY7wSH4T7oHyVfwEr9IU5kV0TJ6mHARE7VQ51G6LbU

{
    "title": "Prueba",
    "author": "Mirar usuario",
    "url": "https://en.wikipedia.org/wiki/Stoicism",
    "likes": 1234
}


###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZhc2t5YXQiLCJpZCI6IjYzMmYwZTZlMjVlZGZjNjMxOGRjMDFhYyIsImlhdCI6MTY2NDAzODYwNiwiZXhwIjoxNjY0MDQyMjA2fQ.Kj0bbC9LksjEIJ4kg9E3E_97bAfvhV4260CNvhBaEgk

{
    "title": "恐ろしいの馬",
    "author": "田中丹次郎",
    "url": "http://www.nhk-corporation.or.jp/",
    "likes": 24
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "寂しいの犬",
    "likes": 1559
}

###